Add more descriptive error if we are in a detached HEAD state

diff --git a/scripts/git-rpm-tools b/scripts/git-rpm-tools
--- a/scripts/git-rpm-tools
+++ b/scripts/git-rpm-tools
@@ -45,6 +45,14 @@ function build_prep() {
     GRT_ART_STORAGE_LOC=${GRT_ART_STORAGE_LOC:-$WORK_DIR}
     echo "Set artifact storage location to $GRT_ART_STORAGE_LOC"
 
+    # Check to make sure we aren't in a detached head state, which can cause issues with git archive
+    if [ -z "$GIT_BRANCH" ] && [ -z "$ABSORB_LOCAL" ] && [ -z "$DIRTY" ]; then
+        git_branch_check=$(git symbolic-ref --quiet HEAD 2> /dev/null)
+        if [ $? -ne 0 ]; then
+            die "Error: HEAD is detached, please specify a branch with -b or use -a to include local changes"
+        fi
+    fi
+
     # If -a (ABSORB_LOCAL) is set, generate and use a temporary stash branch
     # which includes any uncommitted local changes
     # Else if -b is set, use the branch name provided to -b (GIT_BRANCH)
