Various early adjustments

diff --git a/scripts/git-rpm-tools b/scripts/git-rpm-tools
--- a/scripts/git-rpm-tools
+++ b/scripts/git-rpm-tools
@@ -14,6 +14,23 @@ function die() {
     exit ${2:-1}
 }
 
+function runchecks() {
+    commands=("git" "rpmspec" "rpmbuild")
+    for cmd in "${commands[@]}"
+    do
+        if ! command -v $cmd &> /dev/null
+        then
+            die "Error: $cmd not available!"
+        exit
+        fi
+    done
+
+    if ! git status &> /dev/null
+    then
+        die "Error: current directory is not a git repo!"
+    fi
+}
+
 function build_prep() {
     WORK_DIR=$PWD
     echo "Selecting work dir: $WORK_DIR"
@@ -65,7 +82,7 @@ function build_prep() {
 }
 
 function build_pkg() {
-    [ -z "$1" ] && die "Error: rpmbuild needs -bb (RPM), -bs (SRPM), or -ba (both) but no option is provided"
+    [ -z "$1" ] && die "Error: rpmbuild needs -bb (RPM), -bs (SRPM), or -ba (both) but no option is provided!"
     # Build rpm in created tree with selected dist
     echo "Running rpmbuild"
     rpmbuild -v --noclean \
@@ -82,13 +99,16 @@ function build_pkg() {
     # Move artifacts to root dir
     artifacts=()
     case $1 in
-        bb|ba)
+        bb)
             #mv $BUILD_TREE/RPMS/*.rpm $WORK_DIR
             artifacts+=("$BUILD_TREE/RPMS/*.rpm")
-            ;;& # <- note the ampersand will fall through to process ba
-        bs|ba)
+            ;;
+        bs)
             #mv $BUILD_TREE/SRPMS/*.src.rpm $WORK_DIR
             artifacts+=("$BUILD_TREE/SRPMS/*.src.rpm")
+            ;;
+        ba)
+            artifacts+=("$BUILD_TREE/RPMS/*.rpm" "$BUILD_TREE/SRPMS/*.src.rpm")
             ;;
         *)
             warn "Warning: Unsupported build option to rpmbuild: $1, artifacts not moved"
@@ -108,7 +128,8 @@ function build_cleanup() {
 }
 
 function git_rpm_build() {
-    [ -z "$1" ] && die "Error: rpmbuild needs -bb (RPM), -bs (SRPM), or -ba (both) but no option is provided"
+    runchecks
+    [ -z "$1" ] && die "Error: rpmbuild needs -bb (RPM), -bs (SRPM), or -ba (both) but no option is provided!"
     build_prep
     build_pkg $1
     build_cleanup
@@ -142,13 +163,13 @@ case "$cmd" in
     help)
         usage
         ;;
-    bb)
+    bb|"")
         git_rpm_build bb
         ;;
     bs)
         git_rpm_build bs
         ;;
-    ba|"")
+    ba)
         git_rpm_build ba
         ;;
     *)
